spring:
  application:
    name: helpdeskapi

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: ${JWT_EXPIRATION:900000}
  key: ${JWT_KEY:Mnt0A7M1mb0g0r52K36sHyThTOwA5UjrndXeMHZofk06tRHSEYPgELPLbTIxBfOdToHOvWVhhCWha14jacCgSsYTTelu4SZ5S9JLbNVVbJkauo2KCiTgCvUgpdorDfvROz6NNSca2jg3Bm6A9jaFrNIHlfwUD678atJkwJQW11qM61P2g1gGgfb9JvH0dMTYFydJeBrluqwN0AO1cmr05gXCuXTOUUUJlhrTpycttaexE1zf7fVfMiO7IBCRE90HMLXPTXlrhNBFSPeo78qCOfL3yhKzG5bU6Xf8nuH9TzEi12ebjsayD3QcXDNVmoIERsS75YfuspVI86HuQDLXUO9K}